[2022-10-11 06:29:42,183] [builder.py:197]            [INFO]     |====================================================================================================|
[2022-10-11 06:29:42,183] [builder.py:197]            [INFO]     |                              Warner Bros. Collection in Z. 1 - Films                               |
[2022-10-11 06:29:42,183] [builder.py:197]            [INFO]     |====================================================================================================|
[2022-10-11 06:29:42,183] [builder.py:198]            [INFO]     |                                                                                                    |
[2022-10-11 06:29:42,183] [builder.py:200]            [INFO]     | Log Folder Name: Warner Bros. is invalid using Warner Bros                                         |
[2022-10-11 06:29:42,184] [builder.py:201]            [INFO]     |                                                                                                    |
[2022-10-11 06:29:42,184] [builder.py:203]            [INFO]     |================================ Building Definition From Templates ================================|
[2022-10-11 06:29:42,184] [builder.py:211]            [DEBUG]    |                                                                                                    |
[2022-10-11 06:29:42,184] [plex_meta_manager.py:696]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 559, in run_collection
                                                                 |     builder = CollectionBuilder(config, metadata, mapping_name, collection_attrs, library=library, extra=output_str)
                                                                 |   File "/modules/builder.py", line 213, in __init__
                                                                 |     new_attributes = self.metadata.apply_template(name, self.mapping_name, self.data, self.data[methods["template"]])
                                                                 |   File "/modules/meta.py", line 111, in apply_template
                                                                 |     raise Failed(f"{self.data_type} Error: No templates found")
                                                                 | modules.util.Failed: Collection Error: No templates found
                                                                 | 
[2022-10-11 06:29:42,185] [plex_meta_manager.py:697]  [ERROR]    | Collection Error: No templates found
[2022-10-11 06:29:42,185] [plex_meta_manager.py:708]  [INFO]     | 
[2022-10-11 06:29:42,186] [plex_meta_manager.py:709]  [INFO]     |====================================================================================================|
[2022-10-11 06:29:42,186] [plex_meta_manager.py:709]  [INFO]     |                                  Finished Warner Bros. Collection                                  |
[2022-10-11 06:29:42,186] [plex_meta_manager.py:709]  [INFO]     |                                    Collection Run Time: 0:00:00                                    |
[2022-10-11 06:29:42,186] [plex_meta_manager.py:709]  [INFO]     |====================================================================================================|
